### ISSUE TITLE
Remove test-repository.yml?

### ISSUE THREAD

**Issue by spl** [geerlingguy/ansible-role-svn#3]
It seems that you have duplicate tasks for “Create a test repository” and “Set ownership” in both [`tasks/main.yml`](https://github.com/geerlingguy/ansible-role-svn/blob/c1693a64f24c0f4714326c3be0b274546a543349/tasks/main.yml) and [`tasks/test-repository.yml`](https://github.com/geerlingguy/ansible-role-svn/blob/ee6418e6518f9c197c8dbdc3b3a7cc2661a9a2ec/tasks/test-repository.yml), but the ones in `tasks/test-repository.yml` do not use `{{ svn_repository_home }}`. Is `tasks/test-repository.yml` used, or should it be removed?

(This could be a naïve question. I'm new to Ansible. But I didn't find a purpose for `tasks/test-repository.yml`.)

**Comment by spl** [comment]
Also, the main problem is: if `tasks/test-repository.yml` is not necessary, it's a bit misleading. I saw it first, before looking at `tasks/main.yml`, and I was confused about how it was actually working, since there was no `/var/www/svn` directory on my (CentOS) system.

**Comment by geerlingguy** [comment]
Yikes, you're correct—I'm not sure how I left that file in the tasks dir. Thanks for letting me know!
